name: Build and release Industrial Edge app artefact

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Package Edgeshark IE app
        run: |
          go run github.com/thediveo/tiap/cmd/tiap@v0.9.7 \
            deployments/industrial-edge/app \
            --out edgeshark.ieapp \
            --app-version ${{github.ref_name}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            edgeshark.ieapp
            LICENSE